enum ActionTypes {
    FETCH_BEST_PRODUCT_LOAD = "FETCH_BEST_PRODUCT_LOAD",
    FETCH_BEST_PRODUCT_SUCCESS = "FETCH_BEST_PRODUCT_SUCCESS",
    FETCH_BEST_PRODUCT_FAILURE = "FETCH_BEST_PRODUCT_FAILURE",
    FETCH_CART_PRODUCT_LOAD = "  FETCH_CART_PRODUCT_LOAD",
    FETCH_CART_PRODUCT_SUCCESS = "FETCH_CART_PRODUCT_SUCCESS",
    FETCH_CART_PRODUCT_FAILURE = "FETCH_CART_PRODUCT_FAILURE",
}

export default ActionTypes